### ISSUE TITLE
Some questions about the implemantion

### ISSUE THREAD

**Issue by ChuanMeng** [Narabzad/BERTQPP#1]
Hi Negar,
Thank you for sharing your code. I'm quite interested in your paper :-).
I would appreciate it if you can answer my questions.
1. Regarding the target metric, I'd like to make sure that you used MAP@20 in this repo and you report MRR@10 in the paper. I have no idea why you use different setups between the repo and the paper.
2. Could you please release the code for evaluation? I'm eager to reproduce the results in the paper but I'm a little bit unclear how I should do. Given the retrieved documents from BM25 in response to each query, I think I need finally to calculate, e.g., **scipy.stats.pearsonr([predicted MRR@10 scores for each query], [actual MRR@10 scores for each query]**). So these two lists (predicted and actual) should be ranked in descending order or not？ 

Look forward to your reply!

Best wishes,
Chuan

**Comment by Narabzad** [comment]
Hi there,

1. I tried training with different target metrics, they do not show a lot of difference in the performance since there is usually one relevant document per query, MAP and MRR become very close. I actually might have the model trained with both metrics, I can share it with you if it helps. but as I said, there is no significant difference. 

2. yes, this is exactly how you measure the correlation. There is no need to rank them. you should have two lists-- the two lists should be related to exact same query ids, and as you said, one is predicted values and the other one is actual performance ( e.g., MRR@10). You can measure any linear or rank based correlation between the two lists. 

lmk if you have any other questions.
